const REPO = 'Gavloski/Memories';
const API = `https://api.github.com/repos/${REPO}/issues?state=all&per_page=100&sort=created&direction=desc`;
const FALLBACK = [
  {title:'O começo deste lugar',date:'15 set 2026',tags:['recomeço'],excerpt:'Talvez eu não esteja tentando contar minha vida. Talvez esteja apenas tentando não me perder dentro dela.',body:'Este lugar nasceu porque algumas coisas ficam pesadas demais quando existem apenas dentro de mim.\n\nNão quero escrever nomes, procurar culpados ou transformar pessoas em personagens. Quero guardar sensações: o que amei, o que perdi, aquilo que me assustou e tudo o que, mesmo doendo, me fez crescer.\n\nEsta é uma história sem versão definitiva. Apenas eu, tentando ser honesto sobre quem fui e descobrindo quem ainda posso ser.'}
];
let entries=[];let activeTag='todos';
const cleanTitle=t=>t.replace(/^\[DIÁRIO\]\s*/i,'').trim();
const escapeHTML=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const formatBody=s=>s.split(/\n{2,}/).map(p=>`<p>${escapeHTML(p).replace(/\n/g,'<br>')}</p>`).join('');
function parseIssue(issue){const lines=(issue.body||'').split('\n');const tagLine=lines.find(l=>/^sentimentos?:/i.test(l));const tags=tagLine?tagLine.split(':').slice(1).join(':').split(',').map(t=>t.trim().toLowerCase()).filter(Boolean):['memória'];const body=lines.filter(l=>!/^sentimentos?:/i.test(l)).join('\n').trim();return{title:cleanTitle(issue.title),date:new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(issue.created_at)),iso:issue.created_at,tags,body,excerpt:body.replace(/[#>*_`]/g,'').slice(0,165)+(body.length>165?'…':'')}}
function renderFilters(){const tags=['todos',...new Set(entries.flatMap(e=>e.tags))];document.querySelector('#filters').innerHTML=tags.map(t=>`<button class="filter ${t===activeTag?'active':''}" data-tag="${escapeHTML(t)}">${escapeHTML(t)}</button>`).join('')}
function render(){const q=document.querySelector('#search-input').value.toLowerCase();const shown=entries.filter(e=>(activeTag==='todos'||e.tags.includes(activeTag))&&`${e.title} ${e.body} ${e.tags.join(' ')}`.toLowerCase().includes(q));document.querySelector('#entries').innerHTML=shown.length?shown.map((e,i)=>`<article class="entry-card" tabindex="0" data-index="${entries.indexOf(e)}"><div class="entry-meta"><span>${escapeHTML(e.date)}</span><span>${escapeHTML(e.tags[0])}</span></div><h3>${escapeHTML(e.title)}</h3><p>${escapeHTML(e.excerpt)}</p><span class="read-more">Ler página →</span></article>`).join(''):'<p class="loading">Nenhuma página encontrada.</p>';document.querySelectorAll('.entry-card').forEach(c=>{const open=()=>showEntry(entries[+c.dataset.index]);c.addEventListener('click',open);c.addEventListener('keydown',ev=>{if(ev.key==='Enter')open()})})}
function showEntry(e){document.querySelector('#dialog-content').innerHTML=`<p class="eyebrow">${escapeHTML(e.date)} · ${escapeHTML(e.tags.join(' · '))}</p><h2>${escapeHTML(e.title)}</h2><div class="body">${formatBody(e.body)}</div>`;document.querySelector('#entry-dialog').showModal()}
async function load(){try{const res=await fetch(API,{headers:{Accept:'application/vnd.github+json'}});if(!res.ok)throw Error();const data=await res.json();entries=data.filter(i=>!i.pull_request&&/^\[DIÁRIO\]/i.test(i.title)).map(parseIssue);if(!entries.length)entries=FALLBACK}catch{entries=FALLBACK}renderFilters();render();document.querySelector('#last-update').textContent=`${entries.length} ${entries.length===1?'página':'páginas'} desta vida.`}
document.querySelector('#filters').addEventListener('click',e=>{if(!e.target.dataset.tag)return;activeTag=e.target.dataset.tag;renderFilters();render()});document.querySelector('#search-input').addEventListener('input',render);document.querySelector('.dialog-close').onclick=()=>document.querySelector('#entry-dialog').close();document.querySelector('#entry-dialog').addEventListener('click',e=>{if(e.target.tagName==='DIALOG')e.target.close()});const root=document.documentElement;const saved=localStorage.getItem('memories-theme');if(saved==='dark'||(!saved&&matchMedia('(prefers-color-scheme:dark)').matches))root.classList.add('dark');document.querySelector('#theme-toggle').onclick=()=>{root.classList.toggle('dark');localStorage.setItem('memories-theme',root.classList.contains('dark')?'dark':'light')};load();
